apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: az-file-explorer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: az-file-explorer
    spec:
      containers:
      - name: az-file-explorer
        image: julienstroheker/az-file-explorer
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: "YourAzureStorageName"
        - name: STORAGE_ACCOUNT_KEY
          value: "YourAzureStorageKey"
        - name: SHARE_NAME
          value: "YourAzureStorageContainer"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: az-file-explorer-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: az-file-explorer