PROJECT_NAME=az-file-explorer

docker-build:
	docker build -t $(PROJECT_NAME) .

docker-run:
	docker run -it --rm -p 5000:5000 \
		-e STORAGE_ACCOUNT_NAME=<> \
		-e STORAGE_ACCOUNT_KEY=<> \
		-e SHARE_NAME=<> \
		$(PROJECT_NAME)

run: docker-build docker-run